### ISSUE TITLE
Question about Evaluate MDD and NLL

### ISSUE THREAD

**Issue by anhhndo** [zdhNarsil/EB_GFN#2]
Dear Mr. Dinghuai,

Thanks for your great work.

I have a question about estimating MDD.
As in (In Dai et al. (2020)), the MMD result is calculated within a fixed group of 4000 samples, which are loaded from a data file. Your work reports an average of 10 repeat results, each with 4000 samples. It looks like your code is missing some line of code to compute MMD. My question is do you still keep a fixed group of 4000 true samples and repeat sampling distinct 10 groups of GflowNets Sample. Or using distinct 10 groups of 4000 true samples. And, for NLL do you keep 4000 true samples fixed or not.

Thanks Mr. Dinghuai
<img width="576" alt="Untitled" src="https://user-images.githubusercontent.com/45682366/180184029-dc4eeb0c-90bf-4168-b81a-5e59b9447e8b.png">

**Comment by zdhNarsil** [comment]
We use distinct 10 groups of 4000 true samples for MMD. Hope this helps!
